apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: ticketing
build:
  artifacts:
  - image: axuby/auth
    context: auth
    docker:
      dockerfile: Dockerfile
  - image: mongo
    context: auth
    buildpacks:
      builder: gcr.io/buildpacks/builder:v1
deploy:
  kubectl:
    manifests:
    - infra/k8s/auth-depl.yaml
    - infra/k8s/auth-mongo-depl.yaml
    - infra/k8s/ingress-srv.yaml
